export const SEARCH_YELP_INIT = 'SEARCH_YELP_INIT';
export const SEARCH_YELP_SUCCESS = 'SEARCH_YELP_SUCCESS';
export const SEARCH_YELP_FAIL = 'SEARCH_YELP_FAIL';

export const GET_HIT_LIST_INIT = 'GET_HIT_LIST_INIT';
export const GET_HIT_LIST_SUCCESS = 'GET_HIT_LIST_SUCCESS';
export const GET_HITLIST_FAIL = 'GET_HITLIST_FAIL';

export const SAVE_BUSINESS_INIT = 'SAVE_BUSINESS_INIT';
export const SAVE_BUSINESS_SUCCESS = 'SAVE_BUSINESS_SUCCESS';
export const SAVE_BUSINESS_FAIL = 'SAVE_BUSINESS_FAIL';

export const DELETE_BUSINESS_INIT = 'DELETE_BUSINESS_INIT';
export const DELETE_BUSINESS_SUCCESS = 'DELETE_BUSINESS_SUCCESS';
export const DELETE_BUSINESS_FAIL = 'DELETE_BUSINESS_FAIL';

export const GET_MISC_INTERESTS_INIT = 'GET_MISC_INTERESTS_INIT';
export const GET_MISC_INTERESTS_SUCCESS = 'GET_MISC_INTERESTS_SUCCESS';
export const GET_MISC_INTERESTS_FAIL = 'GET_MISC_INTERESTS_FAIL';
