export const SEARCH_YELP_INIT = 'SEARCH_YELP_INIT';
export const SEARCH_YELP_SUCCESS = 'SEARCH_YELP_SUCCESS';
export const SEARCH_YELP_FAIL = 'SEARCH_YELP_FAIL';

export const HIT_LIST_INIT = 'HIT_LIST_INIT';
export const GET_HIT_LIST_SUCCESS = 'GET_HIT_LIST_SUCCESS';
export const GET_HITLIST_FAIL = 'GET_HITLIST_FAIL';


export const SAVE_RESTAURANT_SUCCESS = 'SAVE_RESTAURANT_SUCCESS';
export const SAVE_RESTAURANT_FAIL = 'SAVE_RESTAURANT_FAIL';
